#!/usr/bin/env python3
r"""Generate figures/version-banner.tex from the Jarvis-HEP source logo.

Reproduces the `Jarvis --version` banner on a strict monospace grid so it is byte- and
pixel-faithful to the code:

  * The grid unit is one monospace cell width  w = \jcw  (width of "0").
  * Every row is exactly 2 cells tall (row height = 2w), so block rows tile into solid letters.
  * U+2588 FULL BLOCK  -> a solid rule, exactly 1 cell wide and 2w tall (fills its cell).
  * box-drawing glyphs -> the pmboxdraw glyph, scaled to exactly one 1x2 cell.
  * U+2B24 ⬤ (ICON_PIXEL in versioning.py) -> a circle 2 cells wide whose centre sits at the
    exact vertical middle of the row.
  * the wordmark uses the blue->gold TEXT_GRADIENT_COLORS from versioning.py.

Every glyph inherits its colour from the surrounding \textcolor.  Re-run after editing the logo.

Usage:  python3 tools/gen_version_banner.py [/path/to/jarvishep/card/logo]
"""
import sys, re, os

DEFAULT_LOGO = "/Users/p.zhu/Jarvis-Workshop/Jarvis-HEP/jarvishep/card/logo"
logo = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_LOGO
lines = open(logo, encoding="utf-8").read().splitlines()
while lines and not lines[-1].strip():
    lines.pop()

DOT = "⬤"                      # U+2B24, matches ICON_PIXEL in versioning.py
BLOCK = "█"                    # U+2588 full block
grad = ["2f7fd8","73b8f4","aee4fc","b8ffe4","d5f884","f8f675","ffe95d","ffdc3f"]
cellcolor = {"B":"jdotB","W":"jdotW","Y":"jdotY",".":"jdotD"}

# Collect the box-drawing glyphs actually used by the art (everything non-ASCII that is not the
# full block or the dot), so we can map+scale exactly those.
boxchars = {}
for line in lines:
    text = line[10:]
    if BLOCK in text:                       # an art row
        for ch in text:
            if ch not in (" ", BLOCK, DOT) and ord(ch) > 0x2500:
                boxchars[ch] = format(ord(ch), "04X")

def art_to_tex(text):
    text = re.sub(r"Version:\s*\S+", "Version: @@VER@@", text)
    text = text.replace(" ", "~")
    text = text.replace("@@VER@@", "\\JversionNum{}")
    return text

def line_body(text, gi):
    # Art row: fill blank cells with a background-coloured full block (invisible) so every cell
    # is on the grid; visible block/box glyphs inherit the gradient colour.
    if BLOCK in text:
        inner = "".join("\\textcolor{jtermbg}{%s}" % BLOCK if ch == " " else ch for ch in text)
        return "\\textcolor{jgrad%d}{%s}" % (gi, inner)
    # Prose row (tagline, author+version): keep real spaces.
    return "\\textcolor{jgrad%d}{%s}" % (gi, art_to_tex(text))

o = []
o.append("% AUTO-GENERATED by tools/gen_version_banner.py from jarvishep/card/logo.")
o.append("% Do not edit by hand; re-run the generator if the source logo changes.")
for n,c in [("jdotB","2f7fd8"),("jdotW","ffffff"),("jdotY","f6d33f"),("jdotD","134a8d"),
            ("jtermbg","0d1117"),("jtermres","c9d1d9"),("jtermlbl","8b949e")]:
    o.append("\\definecolor{%s}{HTML}{%s}" % (n,c))
for i,c in enumerate(grad):
    o.append("\\definecolor{jgrad%d}{HTML}{%s}" % (i,c))

# --- The grid -----------------------------------------------------------------------------
# w = one monospace cell width; a row is 2w tall; cells span [-0.5w, 1.5w] (middle at +0.5w).
o.append("\\newlength{\\jcw}")
o.append("% U+2588 full block: a solid 1-cell-wide rule filling the 2w-tall row (current colour).")
o.append("\\newcommand{\\jfullblock}{\\settowidth{\\jcw}{0}\\rule[-0.5\\jcw]{\\jcw}{2\\jcw}}")
o.append("\\newunicodechar{%s}{\\jfullblock}" % BLOCK)
o.append("% box-drawing glyph scaled to exactly one 1x2 cell (current colour).")
o.append("\\newcommand{\\jboxcell}[1]{\\settowidth{\\jcw}{0}\\makebox[\\jcw][l]{\\raisebox{-0.5\\jcw}{\\resizebox{\\jcw}{2\\jcw}{\\pmboxdrawuni{#1}}}}}")
for ch,hx in sorted(boxchars.items(), key=lambda kv: kv[1]):
    o.append("\\newunicodechar{%s}{\\jboxcell{%s}}" % (ch, hx))
o.append("% dot ⬤: a circle 2 cells wide, centred at the row's vertical middle (current colour).")
o.append("% baseline=0pt puts the tikz baseline at the circle centre, so \\raisebox aligns the CENTRE")
o.append("% to the row middle (+0.5w) rather than the circle's bottom.")
o.append("\\newcommand{\\jdotglyph}{\\settowidth{\\jcw}{0}\\makebox[2\\jcw][c]{\\raisebox{0.5\\jcw}{\\tikz[baseline=0pt]\\fill circle[radius=0.9\\jcw];}}}")
o.append("\\newunicodechar{%s}{\\jdotglyph}" % DOT)
o.append("")

# --- The banner ---------------------------------------------------------------------------
o.append("\\newcommand{\\JarvisVersionBanner}{%")
o.append("\\resizebox{\\linewidth}{!}{%")
o.append("\\setlength{\\fboxsep}{16pt}%")
o.append("\\colorbox{jtermbg}{%")
o.append("\\begin{varwidth}{30cm}\\ttfamily\\footnotesize%")

logo_rows = []
for i, line in enumerate(lines):
    cells = line[:8]; text = line[10:]
    dots = "".join("\\textcolor{%s}{%s}" % (cellcolor[ch], DOT) for ch in cells)
    gi = min(i, len(grad)-1)
    logo_rows.append("%s\\hspace{0.6em}%s" % (dots, line_body(text, gi)))
# Logo block: pin the line pitch to exactly one cell-height (2w) so rows tile into solid letters.
o.append("{\\settowidth{\\jcw}{0}\\baselineskip=2\\jcw\\relax \\lineskip=0pt \\lineskiplimit=-\\maxdimen")
o.append("\\\\\n".join(logo_rows))
o.append("\\par}%")
o.append("\\vspace{11pt}%")

res = ["\\textcolor{jtermres}{Resources:}"]
for lbl,val in [("Online docs:","https://pengxuan-zhu-phys.github.io/Jarvis-Docs/"),
                ("Homepage:","https://github.com/Pengxuan-Zhu-Phys/Jarvis-HEP")]:
    res.append("~~\\textcolor{jtermlbl}{%s}~~\\textcolor{jtermres}{%s}" % (lbl.replace(' ','~'), val.replace(' ','~')))
ref1 = "Jarvis-HEP:~A~lightweight~Python~framework~for~workflow"
ref2 = "composition~and~parameter~scans~in~high-energy~physics"
auth = "Author:~Erdong~Guo,~Paul~Jackson,~Jin-Min~Yang,~Pengxuan~Zhu"
arx  = "arXiv:~2604.25557"
res.append("~~\\textcolor{jtermlbl}{Reference:}~~\\textcolor{jtermres}{%s}" % ref1)
res.append("~~~~~~~~~~~~~~\\textcolor{jtermres}{%s}" % ref2)
res.append("~~~~~~~~~~~~~~\\textcolor{jtermres}{%s}" % auth)
res.append("~~~~~~~~~~~~~~\\textcolor{jtermres}{%s}" % arx)
o.append("\\\\[1pt]\n".join(res))
o.append("\\end{varwidth}%")
o.append("}}}")

out = os.path.join(os.path.dirname(__file__) or ".", "..", "figures", "version-banner.tex")
open(out, "w", encoding="utf-8").write("\n".join(o) + "\n")
print("wrote", os.path.normpath(out), "| box glyphs scaled:", " ".join(sorted(boxchars)))
